export const CARBON_CONSTANTS = {
  GRID_INTENSITY_KG_PER_KWH: 0.82,
  AC_POWER_KW: 1.5,
  DELIVERY_VEHICLE_KG: 1.5,
  FLIGHT_DOMESTIC_KG: 200.0,
  FLIGHT_INTERNATIONAL_KG: 1100.0,
  METRO_BUS_FACTOR: 0.032,
  PETROL_CAR_FACTOR: 0.143,
  WEEKS_PER_MONTH: 4.33,
  DEFAULT_COMMUTE_DIST_KM: 15.0,
  COMMUTE_SAVING_RATE: 0.11,
} as const;
